packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  core-js-pure: false
  esbuild: true
  msgpackr-extract: true
  sharp: false
  workerd: true
patchedDependencies:
  alchemy@2.0.0-beta.76: patches/alchemy@2.0.0-beta.76.patch
