packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: false
  workerd: true
minimumReleaseAgeExclude:
  - "@effect/platform-node-shared@4.0.0-rc.109"
  - "@effect/platform-node@4.0.0-rc.109"
  - effect@4.0.0-rc.109
  - mysql2@3.23.3
patchedDependencies:
  alchemy@2.0.0-beta.72: patches/alchemy@2.0.0-beta.72.patch
