/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as InvitationInvitationIdRouteImport } from './routes/invitation.$invitationId'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as SetupEditPersonRouteImport } from './routes/setup.edit-person'
import { Route as SetupFamilyRouteImport } from './routes/setup.family'
import { Route as SetupJoinRouteImport } from './routes/setup.join'
import { Route as SetupPeopleRouteImport } from './routes/setup.people'
import { Route as SetupReadyRouteImport } from './routes/setup.ready'
import { Route as SetupReviewRouteImport } from './routes/setup.review'
import { Route as SetupSavedRouteImport } from './routes/setup.saved'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationInvitationIdRoute = InvitationInvitationIdRouteImport.update({
  id: '/invitation/$invitationId',
  path: '/invitation/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const SetupEditPersonRoute = SetupEditPersonRouteImport.update({
  id: '/edit-person',
  path: '/edit-person',
  getParentRoute: () => SetupRoute,
} as any)
const SetupFamilyRoute = SetupFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => SetupRoute,
} as any)
const SetupJoinRoute = SetupJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => SetupRoute,
} as any)
const SetupPeopleRoute = SetupPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => SetupRoute,
} as any)
const SetupReadyRoute = SetupReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => SetupRoute,
} as any)
const SetupReviewRoute = SetupReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => SetupRoute,
} as any)
const SetupSavedRoute = SetupSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => SetupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/signup': typeof SignupRoute
  '/invitation/$invitationId': typeof InvitationInvitationIdRoute
  '/setup/edit-person': typeof SetupEditPersonRoute
  '/setup/family': typeof SetupFamilyRoute
  '/setup/join': typeof SetupJoinRoute
  '/setup/people': typeof SetupPeopleRoute
  '/setup/ready': typeof SetupReadyRoute
  '/setup/review': typeof SetupReviewRoute
  '/setup/saved': typeof SetupSavedRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/invitation/$invitationId': typeof InvitationInvitationIdRoute
  '/setup/edit-person': typeof SetupEditPersonRoute
  '/setup/family': typeof SetupFamilyRoute
  '/setup/join': typeof SetupJoinRoute
  '/setup/people': typeof SetupPeopleRoute
  '/setup/ready': typeof SetupReadyRoute
  '/setup/review': typeof SetupReviewRoute
  '/setup/saved': typeof SetupSavedRoute
  '/setup': typeof SetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/signup': typeof SignupRoute
  '/invitation/$invitationId': typeof InvitationInvitationIdRoute
  '/setup/edit-person': typeof SetupEditPersonRoute
  '/setup/family': typeof SetupFamilyRoute
  '/setup/join': typeof SetupJoinRoute
  '/setup/people': typeof SetupPeopleRoute
  '/setup/ready': typeof SetupReadyRoute
  '/setup/review': typeof SetupReviewRoute
  '/setup/saved': typeof SetupSavedRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/setup'
    | '/signup'
    | '/invitation/$invitationId'
    | '/setup/edit-person'
    | '/setup/family'
    | '/setup/join'
    | '/setup/people'
    | '/setup/ready'
    | '/setup/review'
    | '/setup/saved'
    | '/setup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/invitation/$invitationId'
    | '/setup/edit-person'
    | '/setup/family'
    | '/setup/join'
    | '/setup/people'
    | '/setup/ready'
    | '/setup/review'
    | '/setup/saved'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/setup'
    | '/signup'
    | '/invitation/$invitationId'
    | '/setup/edit-person'
    | '/setup/family'
    | '/setup/join'
    | '/setup/people'
    | '/setup/ready'
    | '/setup/review'
    | '/setup/saved'
    | '/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRouteWithChildren
  SignupRoute: typeof SignupRoute
  InvitationInvitationIdRoute: typeof InvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$invitationId': {
      id: '/invitation/$invitationId'
      path: '/invitation/$invitationId'
      fullPath: '/invitation/$invitationId'
      preLoaderRoute: typeof InvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/edit-person': {
      id: '/setup/edit-person'
      path: '/edit-person'
      fullPath: '/setup/edit-person'
      preLoaderRoute: typeof SetupEditPersonRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/family': {
      id: '/setup/family'
      path: '/family'
      fullPath: '/setup/family'
      preLoaderRoute: typeof SetupFamilyRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/join': {
      id: '/setup/join'
      path: '/join'
      fullPath: '/setup/join'
      preLoaderRoute: typeof SetupJoinRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/people': {
      id: '/setup/people'
      path: '/people'
      fullPath: '/setup/people'
      preLoaderRoute: typeof SetupPeopleRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/ready': {
      id: '/setup/ready'
      path: '/ready'
      fullPath: '/setup/ready'
      preLoaderRoute: typeof SetupReadyRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/review': {
      id: '/setup/review'
      path: '/review'
      fullPath: '/setup/review'
      preLoaderRoute: typeof SetupReviewRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/saved': {
      id: '/setup/saved'
      path: '/saved'
      fullPath: '/setup/saved'
      preLoaderRoute: typeof SetupSavedRouteImport
      parentRoute: typeof SetupRoute
    }
  }
}

interface SetupRouteChildren {
  SetupEditPersonRoute: typeof SetupEditPersonRoute
  SetupFamilyRoute: typeof SetupFamilyRoute
  SetupJoinRoute: typeof SetupJoinRoute
  SetupPeopleRoute: typeof SetupPeopleRoute
  SetupReadyRoute: typeof SetupReadyRoute
  SetupReviewRoute: typeof SetupReviewRoute
  SetupSavedRoute: typeof SetupSavedRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupEditPersonRoute: SetupEditPersonRoute,
  SetupFamilyRoute: SetupFamilyRoute,
  SetupJoinRoute: SetupJoinRoute,
  SetupPeopleRoute: SetupPeopleRoute,
  SetupReadyRoute: SetupReadyRoute,
  SetupReviewRoute: SetupReviewRoute,
  SetupSavedRoute: SetupSavedRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRouteWithChildren,
  SignupRoute: SignupRoute,
  InvitationInvitationIdRoute: InvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
